### ISSUE TITLE
improve fuzzing

### ISSUE THREAD

**Issue by mmatczuk** [mmatczuk/scylla-go-driver#213]
Move the fuzz tests to `xxx_fuzz_test.go` files, and remove thelper checker in those files 

Example, see https://golangci-lint.run/usage/configuration/
```
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
```

Let's focus on reading from Scylla, there are lots of fuzzers but they are not configured.

A fuzzer to work effectively need a large body of legitimate seed corpuses it later modifies.
Running with 10k empty strings is not inspiring.

Let's focus on FuzzRowsResult and add some legitimate inputs, you can save them by querying Scylla system tables and others.
